# Form implementation generated from reading ui file 'admin_window.ui'
from PyQt6 import QtCore, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName('AdminWindow')
        AdminWindow.resize(1050, 720)
        AdminWindow.setWindowTitle('Администратор')
        self.centralwidget = QtWidgets.QWidget(parent=AdminWindow)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.topLayout = QtWidgets.QHBoxLayout()
        self.labelCurrentUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCurrentUser.setText('Администратор')
        self.topLayout.addWidget(self.labelCurrentUser)
        self.topLayout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        self.pushButtonLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogout.setText('Выйти')
        self.topLayout.addWidget(self.pushButtonLogout)
        self.verticalLayout.addLayout(self.topLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabProducts = QtWidgets.QWidget()
        self.verticalLayoutProducts = QtWidgets.QVBoxLayout(self.tabProducts)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.tabProducts)
        self.lineEditSearch.setPlaceholderText('Поиск по названию')
        self.filterLayout.addWidget(self.lineEditSearch)
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonSearch.setText('Найти')
        self.filterLayout.addWidget(self.pushButtonSearch)
        self.comboBoxCategory = QtWidgets.QComboBox(parent=self.tabProducts)
        self.filterLayout.addWidget(self.comboBoxCategory)
        self.pushButtonFilter = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonFilter.setText('Фильтр')
        self.filterLayout.addWidget(self.pushButtonFilter)
        self.comboBoxSort = QtWidgets.QComboBox(parent=self.tabProducts)
        self.filterLayout.addWidget(self.comboBoxSort)
        self.pushButtonSortUp = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonSortUp.setText('↑')
        self.filterLayout.addWidget(self.pushButtonSortUp)
        self.pushButtonSortDown = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonSortDown.setText('↓')
        self.filterLayout.addWidget(self.pushButtonSortDown)
        self.verticalLayoutProducts.addLayout(self.filterLayout)
        self.tableWidgetProducts = QtWidgets.QTableWidget(parent=self.tabProducts)
        self.verticalLayoutProducts.addWidget(self.tableWidgetProducts)
        self.productButtonsLayout = QtWidgets.QHBoxLayout()
        self.pushButtonAddProduct = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonAddProduct.setText('Добавить товар')
        self.productButtonsLayout.addWidget(self.pushButtonAddProduct)
        self.pushButtonEditProduct = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonEditProduct.setText('Редактировать выбранный товар')
        self.productButtonsLayout.addWidget(self.pushButtonEditProduct)
        self.pushButtonDeleteProduct = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonDeleteProduct.setText('Удалить выбранный товар')
        self.productButtonsLayout.addWidget(self.pushButtonDeleteProduct)
        self.pushButtonRefreshProducts = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonRefreshProducts.setText('Все товары')
        self.productButtonsLayout.addWidget(self.pushButtonRefreshProducts)
        self.verticalLayoutProducts.addLayout(self.productButtonsLayout)
        self.tabWidget.addTab(self.tabProducts, 'Товары')
        self.tabOrders = QtWidgets.QWidget()
        self.verticalLayoutOrders = QtWidgets.QVBoxLayout(self.tabOrders)
        self.tableWidgetOrders = QtWidgets.QTableWidget(parent=self.tabOrders)
        self.verticalLayoutOrders.addWidget(self.tableWidgetOrders)
        self.orderButtonsLayout = QtWidgets.QHBoxLayout()
        self.pushButtonAddOrder = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonAddOrder.setText('Добавить заказ')
        self.orderButtonsLayout.addWidget(self.pushButtonAddOrder)
        self.pushButtonEditOrder = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonEditOrder.setText('Редактировать выбранный заказ')
        self.orderButtonsLayout.addWidget(self.pushButtonEditOrder)
        self.pushButtonDeleteOrder = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonDeleteOrder.setText('Удалить выбранный заказ')
        self.orderButtonsLayout.addWidget(self.pushButtonDeleteOrder)
        self.pushButtonRefreshOrders = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonRefreshOrders.setText('Обновить заказы')
        self.orderButtonsLayout.addWidget(self.pushButtonRefreshOrders)
        self.verticalLayoutOrders.addLayout(self.orderButtonsLayout)
        self.tabWidget.addTab(self.tabOrders, 'Заказы')
        self.verticalLayout.addWidget(self.tabWidget)
        AdminWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=AdminWindow)
        AdminWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)
