# Form implementation generated from reading ui file 'admin_order_dialog.ui'
from PyQt6 import QtCore, QtWidgets


class Ui_AdminOrderDialog(object):
    def setupUi(self, AdminOrderDialog):
        AdminOrderDialog.setObjectName('AdminOrderDialog')
        AdminOrderDialog.resize(480, 340)
        AdminOrderDialog.setWindowTitle('Заказ')
        self.verticalLayout = QtWidgets.QVBoxLayout(AdminOrderDialog)
        self.formLayout = QtWidgets.QFormLayout()
        self.labelClient = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelClient.setText('Клиент')
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelClient)
        self.comboBoxClient = QtWidgets.QComboBox(parent=AdminOrderDialog)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxClient)
        self.labelProduct = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelProduct.setText('Товар')
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelProduct)
        self.comboBoxProduct = QtWidgets.QComboBox(parent=AdminOrderDialog)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxProduct)
        self.labelQuantity = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelQuantity.setText('Количество')
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelQuantity)
        self.spinBoxQuantity = QtWidgets.QSpinBox(parent=AdminOrderDialog)
        self.spinBoxQuantity.setMinimum(1)
        self.spinBoxQuantity.setMaximum(100)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBoxQuantity)
        self.labelDestination = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelDestination.setText('Куда заказать')
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDestination)
        self.comboBoxDestination = QtWidgets.QComboBox(parent=AdminOrderDialog)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxDestination)
        self.labelPlace = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelPlace.setText('Адрес / место')
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPlace)
        self.lineEditPlace = QtWidgets.QLineEdit(parent=AdminOrderDialog)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPlace)
        self.labelStatus = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelStatus.setText('Статус')
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelStatus)
        self.comboBoxStatus = QtWidgets.QComboBox(parent=AdminOrderDialog)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxStatus)
        self.verticalLayout.addLayout(self.formLayout)
        self.labelTotal = QtWidgets.QLabel(parent=AdminOrderDialog)
        self.labelTotal.setText('Сумма: 0')
        self.verticalLayout.addWidget(self.labelTotal)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AdminOrderDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.verticalLayout.addWidget(self.buttonBox)
        QtCore.QMetaObject.connectSlotsByName(AdminOrderDialog)
