# Form implementation generated from reading ui file 'ui\client_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClientWindow(object):
    def setupUi(self, ClientWindow):
        ClientWindow.setObjectName("ClientWindow")
        ClientWindow.resize(900, 650)
        self.centralwidget = QtWidgets.QWidget(parent=ClientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.labelCurrentUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCurrentUser.setObjectName("labelCurrentUser")
        self.topLayout.addWidget(self.labelCurrentUser)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.pushButtonLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogout.setObjectName("pushButtonLogout")
        self.topLayout.addWidget(self.pushButtonLogout)
        self.verticalLayout.addLayout(self.topLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabProducts = QtWidgets.QWidget()
        self.tabProducts.setObjectName("tabProducts")
        self.verticalLayoutProducts = QtWidgets.QVBoxLayout(self.tabProducts)
        self.verticalLayoutProducts.setObjectName("verticalLayoutProducts")
        self.labelHint = QtWidgets.QLabel(parent=self.tabProducts)
        self.labelHint.setObjectName("labelHint")
        self.verticalLayoutProducts.addWidget(self.labelHint)
        self.pushButtonRefreshProducts = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonRefreshProducts.setObjectName("pushButtonRefreshProducts")
        self.verticalLayoutProducts.addWidget(self.pushButtonRefreshProducts)
        self.scrollAreaProducts = QtWidgets.QScrollArea(parent=self.tabProducts)
        self.scrollAreaProducts.setWidgetResizable(True)
        self.scrollAreaProducts.setObjectName("scrollAreaProducts")
        self.scrollAreaWidgetContentsProducts = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsProducts.setGeometry(QtCore.QRect(0, 0, 850, 500))
        self.scrollAreaWidgetContentsProducts.setObjectName("scrollAreaWidgetContentsProducts")
        self.scrollAreaProducts.setWidget(self.scrollAreaWidgetContentsProducts)
        self.verticalLayoutProducts.addWidget(self.scrollAreaProducts)
        self.tabWidget.addTab(self.tabProducts, "")
        self.tabOrders = QtWidgets.QWidget()
        self.tabOrders.setObjectName("tabOrders")
        self.verticalLayoutOrders = QtWidgets.QVBoxLayout(self.tabOrders)
        self.verticalLayoutOrders.setObjectName("verticalLayoutOrders")
        self.pushButtonRefreshOrders = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonRefreshOrders.setObjectName("pushButtonRefreshOrders")
        self.verticalLayoutOrders.addWidget(self.pushButtonRefreshOrders)
        self.tableWidgetOrders = QtWidgets.QTableWidget(parent=self.tabOrders)
        self.tableWidgetOrders.setObjectName("tableWidgetOrders")
        self.tableWidgetOrders.setColumnCount(0)
        self.tableWidgetOrders.setRowCount(0)
        self.verticalLayoutOrders.addWidget(self.tableWidgetOrders)
        self.tabWidget.addTab(self.tabOrders, "")
        self.verticalLayout.addWidget(self.tabWidget)
        ClientWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ClientWindow)
        self.statusbar.setObjectName("statusbar")
        ClientWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ClientWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClientWindow)

    def retranslateUi(self, ClientWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientWindow.setWindowTitle(_translate("ClientWindow", "Клиент"))
        self.labelCurrentUser.setText(_translate("ClientWindow", "Клиент"))
        self.pushButtonLogout.setText(_translate("ClientWindow", "Выйти"))
        self.labelHint.setText(_translate("ClientWindow", "Нажмите на карточку товара, чтобы оформить заказ"))
        self.pushButtonRefreshProducts.setText(_translate("ClientWindow", "Обновить товары"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProducts), _translate("ClientWindow", "Товары"))
        self.pushButtonRefreshOrders.setText(_translate("ClientWindow", "Обновить заказы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOrders), _translate("ClientWindow", "Мои заказы"))
