# Form implementation generated from reading ui file 'manager_window.ui'
from PyQt6 import QtCore, QtWidgets


class Ui_ManagerWindow(object):
    def setupUi(self, ManagerWindow):
        ManagerWindow.setObjectName('ManagerWindow')
        ManagerWindow.resize(1000, 700)
        ManagerWindow.setWindowTitle('Менеджер')
        self.centralwidget = QtWidgets.QWidget(parent=ManagerWindow)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.topLayout = QtWidgets.QHBoxLayout()
        self.labelCurrentUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCurrentUser.setText('Менеджер')
        self.topLayout.addWidget(self.labelCurrentUser)
        self.topLayout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum))
        self.pushButtonLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogout.setText('Выйти')
        self.topLayout.addWidget(self.pushButtonLogout)
        self.verticalLayout.addLayout(self.topLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabProducts = QtWidgets.QWidget()
        self.verticalLayoutProducts = QtWidgets.QVBoxLayout(self.tabProducts)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.tabProducts)
        self.lineEditSearch.setPlaceholderText('Поиск по названию')
        self.filterLayout.addWidget(self.lineEditSearch)
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonSearch.setText('Найти')
        self.filterLayout.addWidget(self.pushButtonSearch)
        self.comboBoxCategory = QtWidgets.QComboBox(parent=self.tabProducts)
        self.filterLayout.addWidget(self.comboBoxCategory)
        self.pushButtonFilter = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonFilter.setText('Фильтр')
        self.filterLayout.addWidget(self.pushButtonFilter)
        self.verticalLayoutProducts.addLayout(self.filterLayout)
        self.sortLayout = QtWidgets.QHBoxLayout()
        self.comboBoxSort = QtWidgets.QComboBox(parent=self.tabProducts)
        self.sortLayout.addWidget(self.comboBoxSort)
        self.pushButtonSortUp = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonSortUp.setText('↑')
        self.sortLayout.addWidget(self.pushButtonSortUp)
        self.pushButtonSortDown = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonSortDown.setText('↓')
        self.sortLayout.addWidget(self.pushButtonSortDown)
        self.pushButtonRefreshProducts = QtWidgets.QPushButton(parent=self.tabProducts)
        self.pushButtonRefreshProducts.setText('Все товары')
        self.sortLayout.addWidget(self.pushButtonRefreshProducts)
        self.verticalLayoutProducts.addLayout(self.sortLayout)
        self.scrollAreaProducts = QtWidgets.QScrollArea(parent=self.tabProducts)
        self.scrollAreaProducts.setWidgetResizable(True)
        self.scrollAreaWidgetContentsProducts = QtWidgets.QWidget()
        self.scrollAreaProducts.setWidget(self.scrollAreaWidgetContentsProducts)
        self.verticalLayoutProducts.addWidget(self.scrollAreaProducts)
        self.tabWidget.addTab(self.tabProducts, 'Товары')
        self.tabOrders = QtWidgets.QWidget()
        self.verticalLayoutOrders = QtWidgets.QVBoxLayout(self.tabOrders)
        self.tableWidgetOrders = QtWidgets.QTableWidget(parent=self.tabOrders)
        self.verticalLayoutOrders.addWidget(self.tableWidgetOrders)
        self.orderStatusLayout = QtWidgets.QHBoxLayout()
        self.comboBoxStatus = QtWidgets.QComboBox(parent=self.tabOrders)
        self.orderStatusLayout.addWidget(self.comboBoxStatus)
        self.pushButtonChangeStatus = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonChangeStatus.setText('Изменить статус выбранного заказа')
        self.orderStatusLayout.addWidget(self.pushButtonChangeStatus)
        self.pushButtonRefreshOrders = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonRefreshOrders.setText('Обновить заказы')
        self.orderStatusLayout.addWidget(self.pushButtonRefreshOrders)
        self.verticalLayoutOrders.addLayout(self.orderStatusLayout)
        self.tabWidget.addTab(self.tabOrders, 'Заказы')
        self.verticalLayout.addWidget(self.tabWidget)
        ManagerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ManagerWindow)
        ManagerWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(ManagerWindow)
