# Form implementation generated from reading ui file 'order_dialog.ui'
from PyQt6 import QtCore, QtWidgets


class Ui_OrderDialog(object):
    def setupUi(self, OrderDialog):
        OrderDialog.setObjectName('OrderDialog')
        OrderDialog.resize(420, 260)
        OrderDialog.setWindowTitle('Оформление заказа')
        self.verticalLayout = QtWidgets.QVBoxLayout(OrderDialog)
        self.labelProduct = QtWidgets.QLabel(parent=OrderDialog)
        self.labelProduct.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelProduct.setText('Товар')
        self.verticalLayout.addWidget(self.labelProduct)
        self.formLayout = QtWidgets.QFormLayout()
        self.labelQuantity = QtWidgets.QLabel(parent=OrderDialog)
        self.labelQuantity.setText('Количество')
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelQuantity)
        self.spinBoxQuantity = QtWidgets.QSpinBox(parent=OrderDialog)
        self.spinBoxQuantity.setMinimum(1)
        self.spinBoxQuantity.setMaximum(100)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBoxQuantity)
        self.labelDestination = QtWidgets.QLabel(parent=OrderDialog)
        self.labelDestination.setText('Куда заказать')
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDestination)
        self.comboBoxDestination = QtWidgets.QComboBox(parent=OrderDialog)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxDestination)
        self.labelPlace = QtWidgets.QLabel(parent=OrderDialog)
        self.labelPlace.setText('Адрес / место')
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPlace)
        self.lineEditPlace = QtWidgets.QLineEdit(parent=OrderDialog)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPlace)
        self.verticalLayout.addLayout(self.formLayout)
        self.labelTotal = QtWidgets.QLabel(parent=OrderDialog)
        self.labelTotal.setText('Сумма: 0')
        self.verticalLayout.addWidget(self.labelTotal)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=OrderDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.verticalLayout.addWidget(self.buttonBox)
        QtCore.QMetaObject.connectSlotsByName(OrderDialog)
