# Form implementation generated from reading ui file 'product_dialog.ui'
from PyQt6 import QtCore, QtWidgets


class Ui_ProductDialog(object):
    def setupUi(self, ProductDialog):
        ProductDialog.setObjectName('ProductDialog')
        ProductDialog.resize(480, 420)
        ProductDialog.setWindowTitle('Товар')
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductDialog)
        self.formLayout = QtWidgets.QFormLayout()
        self.labelName = QtWidgets.QLabel(parent=ProductDialog)
        self.labelName.setText('Название')
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(parent=ProductDialog)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditName)
        self.labelDescription = QtWidgets.QLabel(parent=ProductDialog)
        self.labelDescription.setText('Описание')
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDescription)
        self.plainTextEditDescription = QtWidgets.QPlainTextEdit(parent=ProductDialog)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainTextEditDescription)
        self.labelPrice = QtWidgets.QLabel(parent=ProductDialog)
        self.labelPrice.setText('Цена')
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPrice)
        self.doubleSpinBoxPrice = QtWidgets.QDoubleSpinBox(parent=ProductDialog)
        self.doubleSpinBoxPrice.setDecimals(2)
        self.doubleSpinBoxPrice.setMaximum(999999.0)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.doubleSpinBoxPrice)
        self.labelCategory = QtWidgets.QLabel(parent=ProductDialog)
        self.labelCategory.setText('Категория')
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelCategory)
        self.comboBoxCategory = QtWidgets.QComboBox(parent=ProductDialog)
        self.comboBoxCategory.setEditable(True)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxCategory)
        self.labelImage = QtWidgets.QLabel(parent=ProductDialog)
        self.labelImage.setText('Картинка')
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelImage)
        self.lineEditImage = QtWidgets.QLineEdit(parent=ProductDialog)
        self.lineEditImage.setPlaceholderText('monitor.png')
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditImage)
        self.labelDiscount = QtWidgets.QLabel(parent=ProductDialog)
        self.labelDiscount.setText('Скидка %')
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDiscount)
        self.spinBoxDiscount = QtWidgets.QSpinBox(parent=ProductDialog)
        self.spinBoxDiscount.setMinimum(0)
        self.spinBoxDiscount.setMaximum(99)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBoxDiscount)
        self.labelDiscountDate = QtWidgets.QLabel(parent=ProductDialog)
        self.labelDiscountDate.setText('Скидка до')
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDiscountDate)
        self.dateEditDiscount = QtWidgets.QDateEdit(parent=ProductDialog)
        self.dateEditDiscount.setCalendarPopup(True)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEditDiscount)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ProductDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.verticalLayout.addWidget(self.buttonBox)
        QtCore.QMetaObject.connectSlotsByName(ProductDialog)
